#!/bin/sh

fzf_exclude="--exclude={.git,.local,.cache,.wine,.opam}"

# Use ~~ as the trigger sequence instead of the default **
export FZF_COMPLETION_TRIGGER=',,'

# Options to fzf command
#export FZF_DEFAULT_COMMAND='fd --hidden --follow $fzf_exclude .'
export FZF_DEFAULT_OPTS='--height 80% --border --info=inline --layout=reverse --color=bg+:#343d46,gutter:-1,pointer:#ff3c3c,info:#0dbc79,hl:#0dbc79,hl+:#23d18b'
export FZF_COMPLETION_OPTS='--height 80% --border --info=inline --layout=reverse --color=bg+:#343d46,gutter:-1,pointer:#ff3c3c,info:#0dbc79,hl:#0dbc79,hl+:#23d18b'

# options for ctrl+t
export FZF_CTRL_T_COMMAND='fd --hidden --follow $fzf_exclude .'
export FZF_CTRL_T_OPTS=$FZF_COMPLETION_OPTS

# options for ctrl+r
#export FZF_CTRL_R_COMMAND=''
export FZF_CTRL_R_OPTS=$FZF_COMPLETION_OPTS

# options for alt+c
export FZF_ALT_C_COMMAND='fd --hidden --follow $fzf_exclude --type d .'
export FZF_ALT_C_OPTS="$FZF_COMPLETION_OPTS --preview 'tree -a -C {}' | head -200"


# Use fd (https://github.com/sharkdp/fd) instead of the default find
# command for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  fd --hidden --follow $fzf_exclude . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --hidden $fzf_exclude --type d . "$1"
}

# (EXPERIMENTAL) Advanced customization of fzf options via _fzf_comprun function
# - The first argument to the function is the name of the command.
# - You should make sure to pass the rest of the arguments to fzf.
_fzf_comprun() {
    local command=$1
    shift

    case "$command" in
        cd)           fzf "$@" --preview 'tree -a -C {} | head -200' ;;
        bat)           fzf "$@" --preview 'batcat --style=numbers --color=always --line-range :500 {}' ;;
        export|unset) fzf "$@" --preview "eval 'echo \$'{}" ;;
        ssh)          fzf "$@" --preview 'dig {}' ;;
        *)            fzf "$@" ;;
    esac
}
