#!/bin/sh
# Vim

VIM=nvim
alias vi='$VIM'
alias vim='$VIM'
alias vrc='$VIM $HOME/.config/nvim'

alias vbp='$VIM $ZDOTDIR/zsh-profile'
alias val='$VIM $ZDOTDIR/zsh-aliases'
alias sbp='source $HOME/.zshrc'

# colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# some more ls aliases
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# confirm before overwriting something
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

alias shi='history | grep'
