#!/bin/sh
# Vim

VIM=nvim
alias vi='$VIM'
alias vim='$VIM'
alias virc='$VIM $HOME/.config/nvim'

alias vizrc='$VIM $ZDOTDIR/zsh-profile'
alias vial='$VIM $ZDOTDIR/zsh-aliases'
alias vizsh='$VIM $ZDOTDIR'
alias sozsh='source $HOME/.zshrc'

# colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# some more ls aliases
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# confirm before overwriting something
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# mkdir and rmdir
alias md='mkdir -p'
alias rd='rmdir'

# previous directories
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# go to dotfiles
alias dotfiles='cd $HOME/git/dotfiles'
